tap "argon/mas"
tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "phinze/cask"
tap "rcmdnk/file"
tap "sanemat/font"
tap "supermomonga/splhack"
tap "tldr-pages/tldr"
tap "yudai/gotty"
brew "libnet"
brew "arping"
brew "aspell"
brew "autoconf"
brew "automake"
brew "bash"
brew "libpng"
brew "gettext"
brew "libffi"
brew "pixman"
brew "cloog"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "curl"
brew "czmq"
brew "dfc"
brew "direnv"
brew "docker", link: false
brew "exiftool"
brew "libogg"
brew "icu4c"
brew "little-cms2"
brew "openjpeg"
brew "libvorbis"
brew "xvid"
brew "ffmpeg"
brew "pcre2"
brew "fish"
brew "libtool"
brew "fping"
brew "gauche"
brew "mpfr"
brew "gcc@4.9", link: false
brew "ghostscript", link: false
brew "git"
brew "git-secrets"
brew "global"
brew "gnuplot"
brew "go"
brew "heroku"
brew "highlight"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "iperf"
brew "jbig2dec"
brew "oniguruma"
brew "jq"
brew "libiconv"
brew "libmpc@0.8"
brew "libsodium"
brew "libvo-aacenc"
brew "libxkbcommon"
brew "libxml2", link: true
brew "libxslt", link: true
brew "libzip"
brew "makedepend"
brew "markdown"
brew "mercurial"
brew "mysql"
brew "nkf"
brew "nmap"
brew "nodebrew"
brew "p7zip"
brew "pandoc"
brew "perl"
brew "poppler"
brew "postgresql"
brew "r"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "rlwrap"
brew "rmtrash"
brew "sdl"
brew "shellcheck"
brew "sphinx-doc"
brew "starship"
brew "terminal-notifier"
brew "texi2html"
brew "thefuck"
brew "tmux"
brew "tree"
brew "unrar"
brew "utf8proc"
brew "wget"
brew "xdotool"
brew "yasm"
brew "argon/mas/mas"
brew "rcmdnk/file/brew-file"
brew "sanemat/font/ricty", args: ["with-powerline"]
brew "supermomonga/splhack/cmigemo-mk", args: ["HEAD"]
brew "supermomonga/splhack/ctags-objc-ja", args: ["HEAD"], link: false
brew "tldr-pages/tldr/tldr"
brew "yudai/gotty/gotty"
cask "adobe-reader"
cask "phinze/cask/appcleaner"
cask "phinze/cask/blisk"
cask "phinze/cask/docker"
cask "phinze/cask/dropbox"
cask "phinze/cask/evernote"
cask "phinze/cask/google-chrome"
cask "phinze/cask/google-japanese-ime"
cask "phinze/cask/iterm2"
cask "phinze/cask/kindle"
cask "phinze/cask/skype"
cask "phinze/cask/slack"
cask "phinze/cask/the-unarchiver"
cask "phinze/cask/vagrant"
cask "phinze/cask/virtualbox"
cask "phinze/cask/visual-studio-code"
cask "phinze/cask/vlc"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Realm Browser", id: 1007457278
mas "ToyViewer", id: 414298354
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
